
--Consultas


--Atributos

-- Solicitudes

--ALTER TABLE SOLICITUDES ADD CONSTRAINT restriccion_precio CHECK (precio > 0 AND (precio % 100 = 0));

ALTER TABLE SOLICITUDES ADD CONSTRAINT restriccion_estado CHECK (estado IN ('P', 'A', 'C', 'F'));

ALTER TABLE SOLICITUDES ADD CONSTRAINT restriccion_requerimientos CHECK (REGEXP_LIKE(requerimientos, '^(MUSICA|RUTA|IDIOMA)'));

-- PQRS

ALTER TABLE PQRS ADD CONSTRAINT restriccion_ticked CHECK (REGEXP_LIKE(ticked, '^[A-Z][0-9]{12}$'));

ALTER TABLE PQRS ADD CONSTRAINT restriccion_tipo CHECK (tipo IN ('P', 'Q', 'R', 'S'));

-- Url

ALTER TABLE ANEXOS ADD CONSTRAINT restriccion_url CHECK (REGEXP_LIKE(url_anexo, '^https://.*'));

-- PQRSRESPUESTA

ALTER TABLE  PQRSRESPUESTAS ADD CONSTRAINT CHK_EmailValido_ CHECK (correo LIKE '%@%' AND correo LIKE '%:%'  );

ALTER TABLE PQRSRESPUESTAS ADD CONSTRAINT CHK_RangoValido_ CHECK (evaluacion >= 1 AND evaluacion <= 5);

--Conductores

ALTER TABLE CONDUCTORES ADD CONSTRAINT CHK_Tipo CHECK (Tipo IN ('TI', 'CC', 'CE', 'PS'));

ALTER TABLE CONDUCTORES ADD CONSTRAINT CHK_EmailValido CHECK (correo LIKE '%@%' AND correo LIKE '%:%'  );

ALTER TABLE CONDUCTORES ADD CONSTRAINT CHK_RangoValido CHECK (estrellas >= 1 AND estrellas <= 5);

ALTER TABLE CONDUCTORES ADD CONSTRAINT CHK_EstadoValido CHECK (estado IN ('A', 'I', 'R', 'O'));


--Vehiculos

ALTER TABLE VEHICULOS ADD CONSTRAINT check_año_nacimiento CHECK (a_0 <= 1900);

ALTER TABLE VEHICULOS ADD CONSTRAINT restriccion_nombre CHECK (estado IN ('A', 'I', 'R', 'O'));

ALTER TABLE VEHICULOS ADD CONSTRAINT check_puertas CHECK (puertas > 0);

ALTER TABLE VEHICULOS ADD CONSTRAINT check_pasajeros CHECK (pasajeros > 0);

ALTER TABLE VEHICULOS ADD CONSTRAINT check_carga CHECK (carga > 0);

--Nuevas restricciones 

-- Modificación de la tabla CONDUCTORES para agregar la restricción de longitud de nombre
ALTER TABLE CONDUCTORES ADD CONSTRAINT restriccion_longitud_nombre CHECK (LENGTH(nombre) <= 50);

-- Restricción para latitud y longitud en la tabla INICIAEN
ALTER TABLE INICIAEN ADD CONSTRAINT restriccion_latitud_i CHECK (latitud >= -90 AND latitud <= 90);
ALTER TABLE INICIAEN ADD CONSTRAINT restriccion_longitud_i CHECK (longitud >= -180 AND longitud <= 180);

-- Restricción para latitud y longitud en la tabla FINALIZAEN
ALTER TABLE FINALIZAEN ADD CONSTRAINT restriccion_latitud_f CHECK (latitud >= -90 AND latitud <= 90);
ALTER TABLE FINALIZAEN ADD CONSTRAINT restriccion_longitud_f CHECK (longitud >= -180 AND longitud <= 180);

--5 Nuevas restricciones 

-- Restricción de fecha de nacimiento válida (anterior o igual a una fecha específica)
ALTER TABLE CONDUCTORES ADD CONSTRAINT CHK_FechaNacimiento CHECK (fechaNacimiento <= DATE '2000-12-31');


-- Restricción de precio múltiplo de 100
ALTER TABLE SOLICITUDES ADD CONSTRAINT CHK_PrecioMultiplo100 CHECK (precio > 0 AND MOD(precio, 100) = 0);

-- Restricción de fecha de vencimiento futura (posterior a la fecha actual)
ALTER TABLE TARJETAS ADD CONSTRAINT CHK_FechaVencimiento CHECK (vencimiento > DATE '2023-10-05');


-- Restricción de longitud de descripción
ALTER TABLE PQRSRESPUESTAS ADD CONSTRAINT CHK_LongitudDescripcion CHECK (LENGTH(descripcion) <= 255);

--Retriccion restricción de unicidad en correo
ALTER TABLE CLIENTES ADD CONSTRAINT CHK_CorreoUnico UNIQUE (correo);


--Primarias

ALTER TABLE CONDUCTORES ADD CONSTRAINT PK_CONDUCTORES PRIMARY KEY (id_conductor);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (id_cliente);

ALTER TABLE VEHICULOS ADD CONSTRAINT PK_VEHICULOS PRIMARY KEY (placa);

ALTER TABLE TARJETAS ADD CONSTRAINT PK_TARJETAS PRIMARY KEY (numero);

ALTER TABLE SOLICITUDES ADD CONSTRAINT PK_SOLICITUDES PRIMARY KEY (codigo);

ALTER TABLE PQRS ADD CONSTRAINT PK_PQRS PRIMARY KEY (ticked);

ALTER TABLE INICIAEN ADD CONSTRAINT PK_INICIAEN PRIMARY KEY (latitud, longitud);

ALTER TABLE FINALIZAEN ADD CONSTRAINT PK_FINALIZAEN PRIMARY KEY (latitud, longitud);


--Unicas

ALTER TABLE CONDUCTORES ADD CONSTRAINT UK_CONDUCTORES UNIQUE (tipo, numero);

ALTER TABLE CLIENTES ADD CONSTRAINT UK_CLIENTES UNIQUE (tipo, numero);

ALTER TABLE ANEXOS ADD CONSTRAINT UQ_ANEXOS UNIQUE (url_anexo);


--Foraneas
ALTER TABLE PRESENTA ADD CONSTRAINT FK_PRESENTA_CLIENTES FOREIGN KEY (cliente) REFERENCES CLIENTES (id_cliente);

ALTER TABLE PRESENTA ADD CONSTRAINT FK_PRESENTA_TARJETA FOREIGN KEY (targeta) REFERENCES TARJETAS (numero);

ALTER TABLE VEHICULOS ADD CONSTRAINT FK_VEHICULOS_CONDUCTORES FOREIGN KEY (conductor) REFERENCES CONDUCTORES (id_conductor);

ALTER TABLE SOLICITUDES ADD CONSTRAINT FK_SOLICITUDES_CLIENTES FOREIGN KEY (cliente) REFERENCES CLIENTES (id_cliente); 

ALTER TABLE SOLICITUDES ADD CONSTRAINT FK_SOICITUDES_INCIAEN FOREIGN KEY (latitud,longitud) REFERENCES INICIAEN(latitud,longitud);

ALTER TABLE SOLICITUDES ADD CONSTRAINT FK_SOICITUDES_FINALIZAEN FOREIGN KEY (latitudFin,longitudFin) REFERENCES FINALIZAEN(latitud,longitud); --PORQUE VERGAS DIJISTE QUE SON DOS FORANEAS SI SEGUN TU CODIGO BASURA ESTO ES UNA FOREAN COMPUESTA

ALTER TABLE REQUERIMIENTOS ADD CONSTRAINT FK_SOLICITUDES_REQUERIMIENTOS FOREIGN KEY (solicitud) REFERENCES SOLICITUDES(codigo);
